version: '3.8'

services:
    gateway:
        build:
            context: ./gateway/docker/prod/nginx
        ports:
            - "80:80"
            - "443:443"
        restart: always
        depends_on:
            - frontend
            - api

    frontend:
        build:
            context: ./frontend
            dockerfile: docker/prod/node/Dockerfile
        command: yarn start
        tty: true
        restart: always

    api:
        build:
            context: ./api
            dockerfile: docker/prod/nginx/Dockerfile
        volumes:
            - socket_php:/var/run/php
        restart: always
        depends_on:
            - api-php-fpm

    api-php-fpm:
        build:
            context: ./api
            dockerfile: docker/prod/php-fpm/Dockerfile
        environment:
            APP_SECRET: a7e49f7332381b2a994cb863683d046c
            DATABASE_URL: "postgresql://dev:dev@db:5432/dev?serverVersion=13&charset=utf8"
            MAILER_DSN: smtp://mailer:1025
            MAILER_FROM_EMAIL: mail@app.test
            OAUTH2_ENCRYPTION_KEY: "B7rM540/2ez9KlmZgDJZqlSbeTHXBqRJevgUSlUSZKk="
        volumes:
            - socket_php:/var/run/php
        restart: always

    api-php-cli:
        build:
            context: ./api
            dockerfile: docker/prod/php-cli/Dockerfile
        environment:
            APP_SECRET: a7e49f7332381b2a994cb863683d046c
            DATABASE_URL: "postgresql://dev:dev@db:5432/dev?serverVersion=13&charset=utf8"
            MAILER_DSN: smtp://mailer:1025
            MAILER_FROM_EMAIL: mail@app.test
            OAUTH2_ENCRYPTION_KEY: "B7rM540/2ez9KlmZgDJZqlSbeTHXBqRJevgUSlUSZKk="
        restart: always

    db:
        image: postgres:13.3-alpine
        volumes:
            - db:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: dev
            POSTGRES_USER: dev
            POSTGRES_PASSWORD: dev
        restart: always

volumes:
    socket_php:
    db:
