version: '3.8'

services:
    gateway:
        build:
            context: ./gateway/docker/prod/nginx
        ports:
            - "80:80"
            - "443:443"
        restart: always
        depends_on:
            - frontend
            - api

    frontend:
        image: node:16-alpine
        working_dir: /app
        volumes:
            - ./frontend:/app
        command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && yarn dev"
        tty: true
        restart: always

    frontend-cli:
        image: node:16-alpine
        working_dir: /app
        volumes:
            - ./frontend:/app
        restart: always

    api:
        build:
            context: ./api
            dockerfile: docker/prod/nginx/Dockerfile
        volumes:
            - socket_php:/var/run/php
        restart: always
        depends_on:
            - api-php-fpm

    api-php-fpm:
        build:
            context: ./api/docker
            dockerfile: prod/php-fpm/Dockerfile
#        environment:
        volumes:
            - ./api:/app
            - socket_php:/var/run/php
        restart: always

    api-php-cli:
        build:
            context: ./api/docker
            dockerfile: prod/php-cli/Dockerfile
#        environment:
        volumes:
            - ./api:/app
        restart: always

    db:
        image: postgres:13.3-alpine
        volumes:
            - db:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: dev
            POSTGRES_USER: dev
            POSTGRES_PASSWORD: dev
        restart: always

volumes:
    socket_php:
    db:
