doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '13'
        types:
            user_id: '\App\Model\Entity\User\Type\IdType'
            user_email: '\App\Model\Entity\User\Type\EmailType'
            user_status: '\App\Model\Entity\User\Type\StatusType'
            card_id: '\App\Model\Entity\Card\Type\IdType'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Entity'
                prefix: 'App\Model\Entity'
                alias: App
