---
-   name: Update packages
    apt:
        update_cache: yes

-   name: Install packages
    apt:
        name:
            - apt-transport-https
            - ca-certificates
            - curl
            - gnupg-agent
            - software-properties-common
        state: present
        update_cache: yes

-   name: Add official GPG key
    apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

-   name: Verify GPG key
    apt_key:
        id: 0EBFCD88
        state: present

-   name: Set up the stable repository
    apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
        filename: docker
        update_cache: yes

-   name: Update packages
    apt:
        update_cache: yes

-   name: Install Docker
    apt:
        name:
            - docker-ce
        state: present
        update_cache: yes
    notify: Start Docker on boot

-   name: Install Docker Compose
    get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
        dest: /usr/local/bin/docker-compose
        group: docker
        mode: 'u+x,g+x'

-   name: Set cron Docker prune
    cron:
        name: Docker prune
        job: 'docker system prune -f --filter "until=$((10*24))h"'
        minute: '0'
        hour: '1'

-   name: Remove useless packages from the cache
    apt:
        autoclean: yes

-   name: Remove dependencies that are no longer required
    apt:
        autoremove: yes
